# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 20:08
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('orders', '0002_auto_20170317_2119'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='ShopUser',
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
