# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 11:07
from __future__ import unicode_literals

import apps.shop.utils
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', slugify=apps.shop.utils.slugify_, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=apps.shop.utils.category_img_path, verbose_name='Зображення')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
            options={
                'verbose_name': 'Категорія',
                'ordering': ['name'],
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Виробник')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', slugify=apps.shop.utils.slugify_, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=apps.shop.utils.manufacturer_img_path, verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Виробник',
                'ordering': ['name'],
                'verbose_name_plural': 'Виробники',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Назва')),
                ('model_name', models.CharField(blank=True, max_length=200, verbose_name='Модель')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=apps.shop.utils.base_for_product_slug, slugify=apps.shop.utils.slugify_, unique=True)),
                ('main_image', models.ImageField(blank=True, upload_to=apps.shop.utils.product_main_img_path, verbose_name='Зображення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('stock', models.PositiveIntegerField(verbose_name='На складі')),
                ('available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='shop.Category', verbose_name='Категорія')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_products', to='shop.Manufacturer', verbose_name='Виробник')),
            ],
            options={
                'verbose_name': 'Товар',
                'ordering': ['name'],
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=apps.shop.utils.product_img_path, verbose_name='Зображення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product')),
            ],
        ),
    ]
