# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170201_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Модель'),
        ),
    ]
