# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 10:11
from __future__ import unicode_literals

import apps.shop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170304_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=apps.shop.utils.product_main_img_path, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.shop.utils.product_img_path, verbose_name='Зображення'),
        ),
    ]
