# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:31
from __future__ import unicode_literals

import apps.shop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170305_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.shop.utils.category_img_path, verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.shop.utils.manufacturer_img_path, verbose_name='Зображення'),
        ),
    ]
