# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170306_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Виробник', 'verbose_name_plural': 'Виробники'},
        ),
    ]
