# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:22
from __future__ import unicode_literals

import apps.shop.utils
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20170306_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', slugify=apps.shop.utils.slugify_, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', slugify=apps.shop.utils.slugify_, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', slugify=apps.shop.utils.slugify_, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([]),
        ),
    ]
