# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:50
from __future__ import unicode_literals

import apps.shop.utils
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170308_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=apps.shop.utils.base_for_product_slug, slugify=apps.shop.utils.slugify_, unique=True),
        ),
    ]
